# -*- coding: utf-8 -*-
"""ml_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16aRghPLXq09JPq8liKWAHeCaWYtzelSU
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets
from sklearn.model_selection import train_test_split
import pickle

data = datasets.MNIST('/content',train = True , download = True)

X = data.data
y = data.targets

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.2,shuffle = True)
X_train =  X_train.reshape(-1,28*28)

X_train = torch.tensor(X_train,dtype = torch.float32)/255

Y_train = torch.tensor(y_train,dtype = torch.long)

x_test = torch.tensor(X_test,dtype = torch.float32)/255

class Network(nn.Module):
  def __init__(self,size):
    super().__init__()
    self.linear = nn.Sequential(
        nn.Linear(size,100),
        nn.ReLU(),
        nn.Linear(100,75),
        nn.ReLU(),
        nn.Linear(75,10),
    )

  def forward(self,X):
    out = self.linear(X)
    return out

model = Network(28*28)
optimizer = optim.SGD(model.parameters(),lr = 0.1)
criteria = nn.CrossEntropyLoss()

epoch = 100
for e in range(epoch):

  y_pred = model(X_train)

  loss = criteria(y_pred,Y_train)

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()

  print(loss.item())

print(Y_train)
print(y_pred)

from sklearn.metrics import accuracy_score


print(y_test.shape)

with torch.no_grad():
  y_out = model(x_test.view(-1,28*28))
print(torch.max(y_out).shape)
count = 0
for i in range(0,12000, 10):
  ar = []
  ar.append(y_out[i][0].item())
  ar.append((y_out[i][1]).item())
  ar.append((y_out[i][2]).item())
  ar.append((y_out[i][3]).item())
  ar.append((y_out[i][4]).item())
  ar.append((y_out[i][5]).item())
  ar.append((y_out[i][6]).item())
  ar.append((y_out[i][7]).item())
  ar.append((y_out[i][8]).item())
  ar.append((y_out[i][9]).item())

  if(ar.index(max(ar)) == y_test[i].item()):
    count +=1

  print(ar.index(max(ar))," ",max(ar))

print("correct --> ",count," accuracy -->",count/120)

pickle.dump(model,open('skmodel.pkl','wb'))