# -*- coding: utf-8 -*-
"""ml_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16aRghPLXq09JPq8liKWAHeCaWYtzelSU
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset , DataLoader
import pickle

data = datasets.MNIST('/content',train = True , download = True)

X = data.data
y = data.targets

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.2,shuffle = True)
X_train =  X_train.reshape(-1,28*28)

X_train = torch.tensor(X_train.detach(),dtype = torch.float32)/255

Y_train = torch.tensor(y_train.detach(),dtype = torch.long)

x_test = torch.tensor(X_test.detach(),dtype = torch.float32)/255
x_test = x_test.reshape(-1,28*28)

y_test = torch.tensor(y_test,dtype = torch.long)

class Network(nn.Module):
  def __init__(self,size):
    super().__init__()
    self.linear = nn.Sequential(
        nn.Linear(size,100),
        nn.ReLU(),
        nn.Linear(100,75),
        nn.ReLU(),
        nn.Linear(75,10),
    )

  def forward(self,X):
    out = self.linear(X)
    return out

class Loader(Dataset):
  def __init__(self,x,y):
    self.x = x
    self.y = y
  def __len__(self):
    return self.x.size(0)
  def __getitem__(self,item):
    return self.x[item],self.y[item]

Train_loader = Loader(X_train,y_train)
Train_loader = DataLoader(Train_loader,batch_size = 32,shuffle = True)

test_loader = Loader(X_test,y_test)
Test_loader = DataLoader(test_loader,batch_size = 32 , shuffle = False)

model = Network(28*28)
optimizer = optim.Adam(model.parameters(),lr = 0.001)
criteria = nn.CrossEntropyLoss()

epoch = 100
for e in range(epoch):

  total_loss = 0

  for X,y in Train_loader:

    y_pred = model(X)

    loss = criteria(y_pred,y)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    total_loss += loss.item()
  print(total_loss/len(Train_loader))

print(Y_train)
print(y_pred)

with torch.no_grad():
  # 1. Get model predictions for all test items
  y_out = model(x_test)

  # 2. Get the index of the max value across the 10 outputs (dim=1)
  predictions = torch.argmax(y_out, dim=1)

  # 3. Convert y_test to a PyTorch tensor so it matches the predictions type

  # 4. Count how many predictions match the true values
  count = (predictions == y_test).sum().item()

print("correct --> ", count, " accuracy -->", (count / 12000) * 100, "%")



pickle.dump(model,open('model.pkl','wb'))